---
abstract: 'JSON datatype for Moose'
author:
  - 'Michael Langner'
build_requires:
  Moose: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MooseX-Types-JSON
requires:
  Moose::Util::TypeConstraints: '0'
  MooseX::Types: '0'
  base: '0'
  strict: '0'
  warnings: '0'
version: '0.05'
