--- #YAML:1.0
name:                MooseX-Types-JSON
version:             0.02
abstract:            JSON datatype for Moose
license:             perl
author:              
    - Michael Langner
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    JSON::XS:                      2.00
    Moose:                         0.82
    MooseX::Types:                 0.15
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
